apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deploy-citibike
  namespace: mapr-ts
spec:
  selector:
    matchLabels:
      app: citibike
      name: citibike
  template:
    metadata:
      labels:
         app: citibike
         name: citibike
    spec:
      containers:
      - name: k8-citibike
        image: jameshtsun/citibike
        imagePullPolicy: Always
        command:
          - "/bin/bash"
          - "-c"
          - "/startup.sh"
        env:
        - name:  INFLUXDB_SERVER
          value: "influxdbIP"
        - name:  INFLUXDB_PORT
          value: "8086"
        - name:  MNT_DIR
          value: "/citibike"
        - name:  QUERY_INTERVAL
          value: "30"
        securityContext:
          privileged: true
          capabilities:
            add:
             - SYS_ADMIN
             - SYS_RESOURCE
        volumeMounts:
        - mountPath: /citibike
          name: maprflex
      volumes:
        - name: maprflex
          persistentVolumeClaim:
            claimName: citivolclaim
