kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: securemaprclaim
  namespace: mapr-ts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: influxdb-maprfs
